### ISSUE TITLE
Function "prediction_output_to_trajectories" missing in utils.py

### ISSUE THREAD

**Issue by ers1804** [NVlabs/ScePT#10]
Hello,

I was trying to run your provided notebook `NuScenes Qualitative.ipynb` in `./experiments/nuScenes` but stumbled upon an import error in `./experiments/nuScenes/helper.py`. The import `from utils import prediction_output_to_trajectories` doesn't work because the function isn't defined. Could you provide the code for this function or am I missing something?

Thanks!

**Comment by chenyx09** [comment]
Sorry for the late reply, just pushed the missing util functions.
