### ISSUE TITLE
Map information

### ISSUE THREAD

**Issue by Carrotsniper** [NVlabs/ScePT#11]
Thanks for your fantastic and excellent work.
I am just wondering how you get the map feature of the ETH/UCY dataset.
I can't find map features in this repository.

**Comment by BorisIvanovic** [comment]
There are no vector map features in the ETH/UCY dataset (or at least, the only available information is binary obstacle masks, which are only provided as rasterized images from the original dataset, and even then it is only a subset of the dataset and not all scenarios).
