### ISSUE TITLE
How to use code to generate the predicted lines of driving trajectories?

### ISSUE THREAD

**Issue by xiaoyaocoding** [NVlabs/ScePT#7]
How to use the code in github to generate this picture in the paper?
![image](https://user-images.githubusercontent.com/102663190/227685396-2e82168d-9ecf-4445-be0b-451f57015ab6.png)
I used the plot_snapshot method to generate the following graph, which lacks the colors of different agents and the predicted lines of driving trajectories
![2-30](https://user-images.githubusercontent.com/102663190/227686523-b8edd06c-3e75-4a97-bc7d-4cbf1d7e40c7.png)
Thank you very much！

**Comment by chenyx09** [comment]
I believe those are generated via visualization.plot_trajectories_clique, and it is supposed to generate the colored predicted trajectories. From your figure, it seems that it's ignoring all vehicles, so I suggest you debug into visualization.plot_trajectories_clique function to figure out what happened.

**Comment by YangXS16** [comment]
> How to use the code in github to generate this picture in the paper? ![image](https://user-images.githubusercontent.com/102663190/227685396-2e82168d-9ecf-4445-be0b-451f57015ab6.png) I used the plot_snapshot method to generate the following graph, which lacks the colors of different agents and the predicted lines of driving trajectories ![2-30](https://user-images.githubusercontent.com/102663190/227686523-b8edd06c-3e75-4a97-bc7d-4cbf1d7e40c7.png) Thank you very much！

I am encountering the same problem as you. The picture does not show the trajectories of all the vehicles. Have you solved it now?
