### ISSUE TITLE
ADE on nuscenes vahicles

### ISSUE THREAD

**Issue by papercode202** [NVlabs/ScePT#8]
good morning,
is it possible to get the ADE results on nuscenes Vehicles .
thank you

**Comment by chenyx09** [comment]
Hi, ADE is calculated in the eval_loss function https://github.com/NVlabs/ScePT/blob/b08661dda4f89b496603cab0dec27c40000c0ea1/ScePT/model/ScePT.py#L105C9-L105C18, along with several other metrics.
